name = "newsnow"
pages_build_output_dir = "dist/output/public"
compatibility_date = "2024-10-03"

[[d1_databases]]
binding = "NEWSNOW_DB"
database_name = "newsnow"
database_id = "b3631e9f-1bc2-49ff-bc70-5debef76ff4b"
